[connections.snowflake]
account = "streamlitcommunitycloud-admin_gcp"
user = "ROMANTIC_KALAM_7881190282972354875"
role = "READONLY_ROLE_7881190282972354875"
warehouse = "COMPUTE_WH_7881190282972354875"
private_key_file_path = "./.streamlit/dataset-credentials.p8"
